# Generated by Django 4.2.7 on 2026-08-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRAuthSession',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
